/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCandidaturasRouteImport } from './routes/app.candidaturas'
import { Route as AppImportarRouteImport } from './routes/app.importar'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppCurriculosIndexRouteImport } from './routes/app.curriculos.index'
import { Route as AppCurriculosResumeIdRouteImport } from './routes/app.curriculos.$resumeId'
import { Route as AppVagasIndexRouteImport } from './routes/app.vagas.index'
import { Route as AppVagasJobIdRouteImport } from './routes/app.vagas.$jobId'
import { Route as AppVagasNovaRouteImport } from './routes/app.vagas.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidaturasRoute = AppCandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculosIndexRoute = AppCurriculosIndexRouteImport.update({
  id: '/curriculos/',
  path: '/curriculos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculosResumeIdRoute = AppCurriculosResumeIdRouteImport.update({
  id: '/curriculos/$resumeId',
  path: '/curriculos/$resumeId',
  getParentRoute: () => AppRoute,
} as any)
const AppVagasIndexRoute = AppVagasIndexRouteImport.update({
  id: '/vagas/',
  path: '/vagas/',
  getParentRoute: () => AppRoute,
} as any)
const AppVagasJobIdRoute = AppVagasJobIdRouteImport.update({
  id: '/vagas/$jobId',
  path: '/vagas/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppVagasNovaRoute = AppVagasNovaRouteImport.update({
  id: '/vagas/nova',
  path: '/vagas/nova',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/candidaturas': typeof AppCandidaturasRoute
  '/app/importar': typeof AppImportarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/': typeof AppIndexRoute
  '/app/curriculos/$resumeId': typeof AppCurriculosResumeIdRoute
  '/app/vagas/$jobId': typeof AppVagasJobIdRoute
  '/app/vagas/nova': typeof AppVagasNovaRoute
  '/app/curriculos/': typeof AppCurriculosIndexRoute
  '/app/vagas/': typeof AppVagasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/candidaturas': typeof AppCandidaturasRoute
  '/app/importar': typeof AppImportarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app': typeof AppIndexRoute
  '/app/curriculos/$resumeId': typeof AppCurriculosResumeIdRoute
  '/app/vagas/$jobId': typeof AppVagasJobIdRoute
  '/app/vagas/nova': typeof AppVagasNovaRoute
  '/app/curriculos': typeof AppCurriculosIndexRoute
  '/app/vagas': typeof AppVagasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/candidaturas': typeof AppCandidaturasRoute
  '/app/importar': typeof AppImportarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/': typeof AppIndexRoute
  '/app/curriculos/$resumeId': typeof AppCurriculosResumeIdRoute
  '/app/vagas/$jobId': typeof AppVagasJobIdRoute
  '/app/vagas/nova': typeof AppVagasNovaRoute
  '/app/curriculos/': typeof AppCurriculosIndexRoute
  '/app/vagas/': typeof AppVagasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/candidaturas'
    | '/app/importar'
    | '/app/perfil'
    | '/app/'
    | '/app/curriculos/$resumeId'
    | '/app/vagas/$jobId'
    | '/app/vagas/nova'
    | '/app/curriculos/'
    | '/app/vagas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/candidaturas'
    | '/app/importar'
    | '/app/perfil'
    | '/app'
    | '/app/curriculos/$resumeId'
    | '/app/vagas/$jobId'
    | '/app/vagas/nova'
    | '/app/curriculos'
    | '/app/vagas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/candidaturas'
    | '/app/importar'
    | '/app/perfil'
    | '/app/'
    | '/app/curriculos/$resumeId'
    | '/app/vagas/$jobId'
    | '/app/vagas/nova'
    | '/app/curriculos/'
    | '/app/vagas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidaturas': {
      id: '/app/candidaturas'
      path: '/candidaturas'
      fullPath: '/app/candidaturas'
      preLoaderRoute: typeof AppCandidaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importar': {
      id: '/app/importar'
      path: '/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/curriculos/': {
      id: '/app/curriculos/'
      path: '/curriculos'
      fullPath: '/app/curriculos/'
      preLoaderRoute: typeof AppCurriculosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/curriculos/$resumeId': {
      id: '/app/curriculos/$resumeId'
      path: '/curriculos/$resumeId'
      fullPath: '/app/curriculos/$resumeId'
      preLoaderRoute: typeof AppCurriculosResumeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vagas/': {
      id: '/app/vagas/'
      path: '/vagas'
      fullPath: '/app/vagas/'
      preLoaderRoute: typeof AppVagasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vagas/$jobId': {
      id: '/app/vagas/$jobId'
      path: '/vagas/$jobId'
      fullPath: '/app/vagas/$jobId'
      preLoaderRoute: typeof AppVagasJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vagas/nova': {
      id: '/app/vagas/nova'
      path: '/vagas/nova'
      fullPath: '/app/vagas/nova'
      preLoaderRoute: typeof AppVagasNovaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCandidaturasRoute: typeof AppCandidaturasRoute
  AppImportarRoute: typeof AppImportarRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCurriculosResumeIdRoute: typeof AppCurriculosResumeIdRoute
  AppVagasJobIdRoute: typeof AppVagasJobIdRoute
  AppVagasNovaRoute: typeof AppVagasNovaRoute
  AppCurriculosIndexRoute: typeof AppCurriculosIndexRoute
  AppVagasIndexRoute: typeof AppVagasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidaturasRoute: AppCandidaturasRoute,
  AppImportarRoute: AppImportarRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppCurriculosResumeIdRoute: AppCurriculosResumeIdRoute,
  AppVagasJobIdRoute: AppVagasJobIdRoute,
  AppVagasNovaRoute: AppVagasNovaRoute,
  AppCurriculosIndexRoute: AppCurriculosIndexRoute,
  AppVagasIndexRoute: AppVagasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
